# Generated by Django 3.1.2 on 2021-01-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallionuser',
            name='library',
            field=models.ManyToManyField(to='novels.Novel'),
        ),
    ]
