# Generated by Django 3.1.2 on 2021-01-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
        ('accounts', '0002_stallionuser_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stallionuser',
            name='library',
            field=models.ManyToManyField(blank=True, to='novels.Novel'),
        ),
    ]
