# Generated by Django 3.1.2 on 2020-10-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
