# Generated by Django 3.1.2 on 2021-01-23 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='reads',
        ),
        migrations.AddField(
            model_name='chapter',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='novel',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.category'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover',
            field=models.ImageField(default='novel_covers/ln-cover-1.jpg', upload_to='novel_covers'),
        ),
    ]
