# Generated by Django 3.1.2 on 2020-10-22 07:39

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20201020_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
