# Generated by Django 3.1.2 on 2021-01-23 06:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_auto_20210123_0626'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='novel',
            managers=[
                ('public_novels', django.db.models.manager.Manager()),
            ],
        ),
    ]
