# Generated by Django 3.1.2 on 2021-01-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_auto_20210123_0633'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='novel',
            managers=[
            ],
        ),
    ]
