# Generated by Django 3.1.2 on 2021-01-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_auto_20210123_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='adult',
            new_name='mature',
        ),
        migrations.AddField(
            model_name='chapter',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='genre',
            field=models.CharField(choices=[('UNKNOWN', 'Inconnu'), ('FANTASY', 'Fantasy'), ('ADVENTURE', 'Aventure'), ('ROMANCE', 'Romance')], default='F', max_length=30),
        ),
        migrations.AddField(
            model_name='novel',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
