# Generated by Django 3.1.2 on 2021-01-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_auto_20210126_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover',
            field=models.ImageField(default='novel_covers/default.png', upload_to='novel_covers'),
        ),
    ]
