# Generated by Django 3.1.2 on 2021-01-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_auto_20210127_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='category',
        ),
        migrations.AlterField(
            model_name='novel',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
