# Generated by Django 3.1.2 on 2021-01-28 11:12

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_auto_20210127_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
