# Generated by Django 3.1.2 on 2021-01-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_auto_20210128_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='genre',
            field=models.CharField(choices=[('Inconnu', 'Inconnu'), ('Fantasy', 'Fantasy'), ('Aventure', 'Aventure'), ('Romance', 'Romance')], default='Inconnu', max_length=30),
        ),
    ]
